version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=harmeek
      - DB_PASSWORD=itsokay
      - DB_NAME=social_network_db
      - DB_PORT=5432
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=harmeek
      - POSTGRES_PASSWORD=itsokay
      - POSTGRES_DB=social_network_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: